baseurl = ""
theme = "hugo-geo"
themesdir = "themes"
relativeURLs = false
languageCode = "en-us"
title = "Jeffrey W. Hollister"
disqusShortname = "jhollist"
paginate = 5
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	email = "jeff.w.hollister@gmail.com"
  #stash profile pic in static/img
	profilepic = "conference_jeff.jpg"
	
	title = "Jeffrey W. Hollister"
	subtitle = "Landscape Ecology, Lakes, GIS, R, and Open Science"

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/jhollist"
	[[params.socialbuttons]]
	faicon = "twitter"
	url = "https://twitter.com/jhollist"
	#[[params.socialbuttons]]
	#faicon = "email"
	#url = "mailto:jeff.w.hollister@gmail.com"
	#[[params.socialbuttons]]
	#faicon = "google-plus"
	#url = "https://plus.google.com/+YourID"

	[[params.navlinks]]
	name = "About"
	url = "about"
	
	[[params.navlinks]]
	name = "Blog"
	url = ""
	
	[[params.navlinks]]
	name = "Curriculum Vitae"
	url = "cv.html"
	
	#[[params.navlinks]]
	#name = "Tutorials"
	#url = "tutorial/"
